#!/bin/bash

# Get random image file name
IMG_NAME=$(ls /home/main/Pictures/Wallpapers | shuf -n 1)
# full path to that random image file
IMG_PATH=/home/main/Pictures/Wallpapers/$IMG_NAME
# Command to change wallpaper
awww img $IMG_PATH --transition-type grow --transition-pos 0,1080 --transition-fps 60 --transition-step 60
